# Generated by Django 6.0.4 on 2026-04-24 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('COMIDA', 'Comida'), ('CENA', 'Cena'), ('AFTERWORK', 'Afterwork'), ('TRIAL', 'Trial')], default='COMIDA', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duracion_dias', models.PositiveIntegerField(default=30)),
                ('incluye_desayunos', models.PositiveIntegerField(default=0)),
                ('incluye_comidas', models.PositiveIntegerField(default=0)),
                ('incluye_cenas', models.PositiveIntegerField(default=0)),
                ('incluye_afterworks', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(limit_choices_to={'es_hostelero': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('usos_desayuno', models.PositiveIntegerField(default=0)),
                ('usos_comida', models.PositiveIntegerField(default=0)),
                ('usos_cena', models.PositiveIntegerField(default=0)),
                ('usos_afterwork', models.PositiveIntegerField(default=0)),
                ('esta_activa', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesa.plansuscripcion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('COMIDA', 'Comida'), ('CENA', 'Cena'), ('AFTERWORK', 'Afterwork'), ('TRIAL', 'Trial')], max_length=20)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa.restaurante')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
