# Generated by Django 6.0.4 on 2026-04-24 08:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurante',
            new_name='Establecimiento',
        ),
        migrations.RenameField(
            model_name='ticketcanje',
            old_name='restaurante',
            new_name='establecimiento',
        ),
    ]
