# Generated by Django 6.0.4 on 2026-04-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0002_rename_restaurante_establecimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establecimiento',
            name='dueno',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='ticketcanje',
            name='fecha_canje',
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cupo_afterwork',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cupo_cena',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cupo_comida',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='cupo_desayuno',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='dueño',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='codigo_manual',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='comision_calculada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='datos_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('CANJEADO', 'Canjeado'), ('CADUCADO', 'Caducado/No-Show')], default='RESERVADO', max_length=20),
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='precio_suscripcion_momento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ticketcanje',
            name='token_qr',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ticketcanje',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesa.establecimiento'),
        ),
    ]
