# Generated by Django 6.0.4 on 2026-04-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesa', '0003_remove_establecimiento_dueno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cupo_maximo', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Borrador', max_length=20)),
                ('nombre_lugar_manual', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_manual', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesa.establecimiento')),
            ],
        ),
    ]
